# Generated by Django 5.0.3 on 2024-03-25 00:00

import sound_recorder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to=sound_recorder.models.recording_file_path),
        ),
    ]
