# Generated by Django 5.0.3 on 2024-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_recorder', '0002_alter_recording_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
